### ISSUE TITLE
Regarding ref set 

### ISSUE THREAD

**Issue by tacack** [IHTSDO/sct-snapshot-rest-api#39]
Hello team,

This is more of a please help rather than an issue but i didn’t know any other place to post it. I’m trying to use a new simpler refset that was released by India. Using the snomed CT api, I’m able to search the entire snomed CT DB whichcurrently resides in mongo. Can someone please guide me how to only search within the refset? 

Thanks!
Vybhav

**Comment by tacack** [comment]
Thanks @kaicode 

I'm trying to search within the Indian Neurosurgeory refset that was published. When I try using the **refsetID** seen in the picture below in the "### refsetFilter" value in the API call, I don't get any responses.

<img width="1230" alt="screen shot 2018-12-17 at 5 42 42 pm" src="https://user-images.githubusercontent.com/6650162/50086601-977a5b00-0223-11e9-8b7b-1e6c356213eb.png">

I'm sure I'm doing something wrong. Sorry if I'm off-topic, but I'm stuck and any help is appreciated.

Regards,
Vybhav

**Comment by kaicode** [comment]
Hi @tacack I'm assuming you have loaded the content from India into your own sct-snapshot-rest-api installation.

You are correct to take the `1231000189105` number from the refsetId column of the reference set RF2 file.

Here are some things to try:

- You can check that the content has loaded using the members endpoint:
https://snomedctsnapshotapi.docs.apiary.io/#reference/concepts/children/retrieve-reference-set-members. 
If you set the sctid to `1231000189105` you should get a list of concepts from that reference set.
Here is an example in the public browser using the _450970008 |General Practice / Family Practice reference set (foundation metadata concept)|_: https://browser.ihtsdotools.org/api/v1/snomed/en-edition/v20180731/concepts/450970008/members?limit=100

- You could check your URL format matches this example of using filtering in the public browser using the same GPFP reference set: https://browser.ihtsdotools.org/api/v1/snomed/en-edition/v20180731/descriptions?query=pregnant&refsetFilter=450970008
There are only 7 results when the refsetFilter is used and 79 without so this example appears to be working.

**Comment by tacack** [comment]
Thanks for your response @kaicode . 

Regarding the content, I've loaded the International edition of SNOMED CT. 

<img width="1141" alt="screen shot 2018-12-17 at 8 28 50 pm" src="https://user-images.githubusercontent.com/6650162/50094961-65c0be80-023a-11e9-8c1e-fce4ec4f5eff.png">

I tried the first URL that you mentioned and when I add the SCT ID as 1231000189105, I don't see any results. 

The second URL is precisely the format i'm using for my autocomplete search and it fails to return any results when I include 1231000189105 as the refsetFilter.

Regards,
Vybhav

**Comment by kaicode** [comment]
Hi @tacack, the 1231000189105 reference set is not included in the International Edition of SNOMED CT. This is why you can not find any content relating to that reference set. You will need to load a SNOMED extension or edition containing that reference set in order to use that content. I hope that helps.

**Comment by tacack** [comment]
Hello,

I checked the release notes of the Refsets and I saw this -> 

> This release includes 30 refsets covering common diseases under National Public Health Programs and Medical Specialty / Department-wise refsets.
> 
> 
> This package depends on the SNOMED CT July 2017 International Edition, and should be used and analyzed accordingly.
> 
> Please refer to the Release Note downloadable from this MLDS release package. The release note is also available at NRCeS website (https://www.nrces.in)
> 

When it says it depends on the July 2017 international edition, is it safe to assume that the 2018 Jan 1st international edition will also have the changes?

Thanks!
Vybhav

**Comment by kaicode** [comment]
If a SNOMED package depends on a specific version of another package it is not safe to assume that a later version will contain all the same content. SNOMED CT concepts can be made inactive when they are no longer wanted in an edition so later releases may not contain all the same active concepts.
It sounds like you will need to load the July 2017 International Edition at the same time as the India Reference Sets extension in order to use this content in the sct-snapshot-rest-api.

I assume that is possible with the rf2-to-json-conversion project.

The other option for loading, managing and querying this content is to use a Terminology Server like Snowstorm for your SNOMED content API. 

This would give you the following advantages:
- Ability to load content into the API using RF2 zip files directly (automatic RF2 to JSON conversion) 
- Store many releases and extensions of of SNOMED CT using Terminology Server branches (like a version control system)
- Ability to load reference set packages after loading the International Edition on a child branch
- Combine description search with [Expression Constraint Language](http://snomed.org/ecl) search to constrain by reference set, SNOMED hierarchy, part of the body or any other SNOMED attribute.

Snowstorm is a free Open Source Terminology Server written for SNOMED CT by Snomed International - https://github.com/IHTSDO/snowstorm

**Comment by tacack** [comment]
I'm going to check out Snowstorm. Thank you for all your help @kaicode . I'll try Snowstorm, downgrade to the July 2017 version and give it a shot. 

Again, appreciate all your help!

**Comment by kaicode** [comment]
👍 
Don't hesitate to ask questions Snowstorm issues/questions section 😸
